export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const GET_PRODUCTS_REVIEWS = 'GET_PRODUCTS_REVIEWS';
export const GET_PRODUCTS_REVIEWS_SUCCESS = 'GET_PRODUCTS_REVIEWS_SUCCESS';
export const GET_PRODUCTS_REVIEWS_ERROR = 'GET_PRODUCTS_REVIEWS_ERROR';

export const SET_PRODUCT_REVIEW = 'SET_PRODUCT_REVIEW';
export const SET_PRODUCT_REVIEW_SUCCESS = 'SET_PRODUCT_REVIEW_SUCCESS';
export const SET_PRODUCT_REVIEW_ERROR = 'SET_PRODUCT_REVIEW_ERROR';